name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Visualizando variables secretas
        run: echo ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.BUILD_ARG_BACKEND_URL }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VITE_BACKEND_URL: ${{ secrets.BUILD_ARG_BACKEND_URL }}
          tags: |
            ajorgenmarten/tickets-portal:${{ github.sha }}
            ajorgenmarten/tickets-portal:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Remose ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          key: ${{ secrets.HOST_SSHKEY }}
          username: ${{ secrets.HOST_USERNAME }}
          script: |
            cd projects/alicia

            docker pull ajorgenmarten/tickets-portal:latest || true

            docker compose down tickets-portal
            docker compose up --build -d tickets-portal

            docker image prune -f

            



