name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/alicia-tickets-web:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/alicia-tickets-web:latest
          build-args: |
            VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}
            VITE_ORCHESTRATOR_URL=${{ secrets.VITE_ORCHESTRATOR_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Remose ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          password: ${{ secrets.HOST_PASSWORD }}
          username: ${{ secrets.HOST_USERNAME }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/alicia-tickets-web:${{ github.sha }}

            docker stop alicia-tickets-web || true

            docker rm alicia-tickets-web || true

            docker run --name alicia-tickets-web -d -p ${{ secrets.PORT }}:80 ${{ secrets.DOCKER_USERNAME }}/alicia-tickets-web:${{ github.sha }}

            docker image prune -f
